# Generated by Django 3.0.6 on 2020-06-06 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ticket',
            name='second_row',
            field=models.CharField(default=2, max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_ticket',
            name='third_row',
            field=models.CharField(default=4, max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
