# Generated by Django 3.0.6 on 2020-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0002_auto_20200606_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ticket',
            name='first_row',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='second_row',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='third_row',
            field=models.CharField(max_length=100),
        ),
    ]
