# Generated by Django 3.0.6 on 2020-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_auto_20200607_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ticket',
            name='first_row',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='second_row',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_ticket',
            name='third_row',
            field=models.CharField(max_length=100),
        ),
    ]
