# Generated by Django 3.0.7 on 2020-07-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0006_save_random_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_row', models.CharField(max_length=100)),
                ('second_row', models.CharField(max_length=100)),
                ('third_row', models.CharField(max_length=100)),
                ('full_house', models.CharField(max_length=100)),
                ('juldi_five', models.CharField(max_length=100)),
                ('corner', models.CharField(max_length=100)),
            ],
        ),
    ]
